// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbj1AYHyuf82rsMKO5hbl9OKs6jSXD68s',
    appId: '1:476553703080:web:6ebcffc148b711a8ae9c9d',
    messagingSenderId: '476553703080',
    projectId: 'peasyprints-4bd2d',
    authDomain: 'peasyprints-4bd2d.firebaseapp.com',
    storageBucket: 'peasyprints-4bd2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6wfuw4WOfyxpioX2UXlzHP8CTsazw-1U',
    appId: '1:476553703080:android:dd2fc25b326d684fae9c9d',
    messagingSenderId: '476553703080',
    projectId: 'peasyprints-4bd2d',
    storageBucket: 'peasyprints-4bd2d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbj1AYHyuf82rsMKO5hbl9OKs6jSXD68s',
    appId: '1:476553703080:web:e70dbc5b22476f3dae9c9d',
    messagingSenderId: '476553703080',
    projectId: 'peasyprints-4bd2d',
    authDomain: 'peasyprints-4bd2d.firebaseapp.com',
    storageBucket: 'peasyprints-4bd2d.firebasestorage.app',
  );
}
